In [17]:
import pandas as pd 
import numpy as np 
import openpyxl
import re

In [27]:
df = pd.read_excel("/Users/aryanbhardwaj78/Desktop/SEM 1 - 2026/DATA 7001 Intro to Data Science/Project - student mental health/data7001_group15_project/raw_data/Dataset for Analyzing University Students Behaviour.xlsx")
df.head(5)

,"Semester( number like: 1st, 2nd...)","Age( Years: 18, 19....)",Height( inches like:1 feet),Weight:( in kg),Gender,Religion,Permanent Residence,Current Residence,Family Type,"Number of siblings (numbers: 1, 2...)",...,I found it difficult to relax,\n I felt down-hearted and blue,I was intolerant of anything that kept me from getting on with what I was doing,I felt I was close to panic,I was unable to become enthusiastic about anything,I felt I wasn’t worth much as a person,I felt that I was rather touchy,"I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)",I felt scared without any good reason,I felt that life was meaningless
0,5th,24,5.6,54,Male,Islam,Urban,Rented House or Mess,Nuclear,3,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
1,8th,21,5.1,46 kg,Female,Islam,Rural,Rented House or Mess,Nuclear,2,...,Applied to me to a considerable degree or a go...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
2,8th,22,5 feet,50 kg,Female,Islam,Rural,Own House,Nuclear,0,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
3,7th,22,5 feet 2 inch,63,Female,Islam,Urban,Own House,Nuclear,2,...,Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me very much or most of the time,"Applied to me to some degree, or some of the time",Applied to me very much or most of the time,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time
4,5th,23,"5.5""",62kg,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time"

In [28]:
df.columns = df.columns.str.strip()

In [29]:
df = df.rename(columns={
    df.columns[0]: 'Semester',
    df.columns[1]: 'Age(in years)',
    df.columns[2]: 'Height(in ft)',
    df.columns[3]: 'Weight(in kg)'
})

In [31]:
#function to clean semester column
def clean_semester(val):
    if pd.isna(val):
        return np.nan
    
    val = str(val).lower().strip()
    
    match = re.search(r'(\d+)', val)
    if match:
        return int(match.group(1))
    
    return np.nan

df['Semester'] = df['Semester'].apply(clean_semester).astype('Int64')

In [40]:
df[df['Semester'].isna()]

,Semester,Age(in years),Height(in ft),Weight(in kg),Gender,Religion,Permanent Residence,Current Residence,Family Type,"Number of siblings (numbers: 1, 2...)",...,I found it difficult to relax,I felt down-hearted and blue,I was intolerant of anything that kept me from getting on with what I was doing,I felt I was close to panic,I was unable to become enthusiastic about anything,I felt I wasn’t worth much as a person,I felt that I was rather touchy,"I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)",I felt scared without any good reason,I felt that life was meaningless
119,<NA>,24,5 feet 4 inches,62,Female,Islam,Urban,Own House,Nuclear,1,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Did not apply to me at all,Applied to me to a considerable degree or a go...,Applied to me very much or most of the time,Applied to me to a considerable degree or a go...
172,<NA>,25,5.6,58,Male,Islam,Rural,Own House,Join or Extended,01301123920,...,Did not apply to me at all,Did not apply to me at all,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time,Did not apply to me at all,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me to a considerable degree or a go...
220,<NA>,23,5feet 1,58,Female,Islam,Urban,Rented House or Mess,Join or Extended,2,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
333,<NA>,24,5.5,58,Male,Islam,Rural,Rented House or Mess,Join or Extended,1,...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...

In [43]:
#there are 4 na values in semester.
#we will impute the most occuring value in place of na
highest_occuring_sem = df['Semester'].mode()[0]
highest_occuring_sem

np.int64(5)

In [45]:
df['Semester'] = df['Semester'].fillna(highest_occuring_sem)

In [47]:
df['Semester'].isna().sum()

np.int64(0)

In [48]:
#Clean age column
df['Age(in years)'] = pd.to_numeric(df['Age(in years)'], errors='coerce')
df['Age(in years)'] = df['Age(in years)'].round()
df['Age(in years)'] = df['Age(in years)'].astype('Int64')

In [49]:
df['Age(in years)'].head(10)

0    24
1    21
2    22
3    22
4    23
5    22
6    22
7    23
8    22
9    22
Name: Age(in years), dtype: Int64

In [50]:
df['Age(in years)'].isna().sum()

np.int64(4)

In [51]:
df[df['Age(in years)'].isna()]

,Semester,Age(in years),Height(in ft),Weight(in kg),Gender,Religion,Permanent Residence,Current Residence,Family Type,"Number of siblings (numbers: 1, 2...)",...,I found it difficult to relax,I felt down-hearted and blue,I was intolerant of anything that kept me from getting on with what I was doing,I felt I was close to panic,I was unable to become enthusiastic about anything,I felt I wasn’t worth much as a person,I felt that I was rather touchy,"I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)",I felt scared without any good reason,I felt that life was meaningless
130,9,<NA>,5 feet 4 inch,58 kg,Male,Islam,Urban,Rented House or Mess,Nuclear,numbers: 1,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
213,9,<NA>,"5""10'",84,Male,Islam,Rural,Rented House or Mess,Join or Extended,3,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
334,4,<NA>,5 feet 3 inch,42,Female,Islam,Urban,Rented House or Mess,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
335,4,<NA>,5 feet 4 inch,65,Male,Islam,Rural,Own House,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all

In [52]:
#Imputing na values in age column with mean(age)
mean_age = df['Age(in years)'].mean()
df['Age(in years)'] = df['Age(in years)'].fillna(round(mean_age))

In [71]:
df['Age(in years)'].isna().sum()

np.int64(0)

In [ ]:
#clean height column
import numpy as np
import re

def clean_height(val):
    if pd.isna(val):
        return np.nan


    if isinstance(val, (int, float)):
        return float(val)

    val = str(val).lower().strip()


    val = val.replace('"', '')
    val = val.replace("''", '')
    val = val.replace("'", ' ')
    val = re.sub(r'\s+', ' ', val).strip()

  
    if re.fullmatch(r'\d+\.\d+', val):
        return float(val)

    match = re.fullmatch(r'(\d+)\s+(\d+)', val)
    if match:
        feet = match.group(1)
        inches = match.group(2)
        return float(f"{feet}.{inches}")


    match = re.search(r'(\d+)\s*feet?\s*(\d+)', val)
    if match:
        feet = match.group(1)
        inches = match.group(2)
        return float(f"{feet}.{inches}")

    match = re.search(r'(\d+)\s*feet?', val)
    if match:
        return float(match.group(1))


    if re.fullmatch(r'\d+', val):
        return float(val)

    return np.nan

In [76]:
df['Height(in ft)'] = df['Height(in ft)'].apply(clean_height)

In [77]:
df.head(25)

,Semester,Age(in years),Height(in ft),Weight(in kg),Gender,Religion,Permanent Residence,Current Residence,Family Type,"Number of siblings (numbers: 1, 2...)",...,I found it difficult to relax,I felt down-hearted and blue,I was intolerant of anything that kept me from getting on with what I was doing,I felt I was close to panic,I was unable to become enthusiastic about anything,I felt I wasn’t worth much as a person,I felt that I was rather touchy,"I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)",I felt scared without any good reason,I felt that life was meaningless
0,5,24,5.5,54,Male,Islam,Urban,Rented House or Mess,Nuclear,3,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
1,8,21,5.1,46 kg,Female,Islam,Rural,Rented House or Mess,Nuclear,2,...,Applied to me to a considerable degree or a go...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
2,8,22,5.0,50 kg,Female,Islam,Rural,Own House,Nuclear,0,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
3,7,22,5.2,63,Female,Islam,Urban,Own House,Nuclear,2,...,Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me very much or most of the time,"Applied to me to some degree, or some of the time",Applied to me very much or most of the time,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time
4,5,23,NaN,62kg,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time"
5,4,22,5.6,56,Male,Islam,Urban,Rented House or Mess,Nuclear,1,...,Applied to me very much or most of the time,Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me very much or most of the time,Did not apply to me at all,"Applied to me to some degree, or some of the time",Applied to me very much or most of the time,Applied to me very much or most of the time,Did not apply to me at all
6,7,22,5.6,73,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
7,6,23,NaN,72,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...
8,7,22,5.7,58,Male,Islam,Urban,Rented House or Mess,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Applied to me to a considerable degree or a go...,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...
9,5,22,5.6,63 kg,Male,Islam,Rural,Rented House or Mess,Join or Extended,4,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all
10,6,22,5.6,70,Male,Islam,Rural,Own House,Nuclear,1,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
11,5,22,5.8,65kg,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
12,5,22,6.0,73,Male,Islam,Rural,Own House,Nuclear,0,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...
13,4,22,4.0,57,Male,Islam,Urban,Rented House or Mess,Join or Extended,3,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,"Applied to me to some degree, or some of the time"
14,4,22,8.0,55,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,"Applied to me to some degree, or some of the time",Applied to me very much or most of the time,Applied to me very much or most of the time,"Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,Did not apply to me at all,Applied to me very much or most of the time,Did not apply to me at all,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time"
15,4,22,5.6,71,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Applied to me very much or most of the time,Did not apply to me at all,Did not apply to me at all
16,8,22,5.3,64,Female,Islam,Urban,Own House,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
17,7,22,5.2,45,Female,Islam,Urban,Own House,Nuclear,2,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time
18,8,23,5.1,63,Female,Islam,Rural,Own House,Nuclear,1,...,Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time
19,5,21,5.2,52,Male,Islam,Rural,Rented House or Mess,Nuclear,3,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
20,8,23,5.2,45,Female,Islam,Rural,Own House,Nuclear,2,...,Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,Applied to me to a considerable degree or a go...,"Applied to me to some degree, or some of the time"
21,4,22,5.4,68,Male,Islam,Rural,Rented House or Mess,Nuclear,1,...,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all
22,5,20,5.5,58,Male,Islam,Rural,Rented House or Mess,Join or Extended,2,...,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time,Applied to me very much or most of the time,Did not apply to me at all,Did not apply to me at all,Did not apply to me at all,Applied to me very much or most of the time
23,7,22,9.0,65,Male,Islam,Urban,Own House,Nuclear,1,...,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time,"Applied to me to some degree, or some of the time",Applied to me to a considerable degree or a go...,Applied to me very much or most of the time,Applied to me very much or most of the time,"Applied to me to some degree, or some of the time","Applied to me to some degree, or some of the time",Applied to me very much or most of the time
24,5,21,5.7,65-70,Male,Islam,Urban,Rented House or Mess,Nuclear,0,...,"Applied to me to some degree, or some of the time",Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Did not apply to me at all,Applied to me very much or most of the time,Did not apply to me at all,"Applied to me to some degree, or some of the time",Did not apply to me at all,Applied to me very much or most of the time

In [78]:
df['Height(in ft)'].isna().sum()

np.int64(32)

In [79]:
#imputing na with mean height
mean_height = df['Height(in ft)'].mean()
df['Height(in ft)'] = df['Height(in ft)'].fillna(mean_height)

In [80]:
df['Height(in ft)'].isna().sum()

np.int64(0)

In [84]:
df['Height(in ft)'] = df['Height(in ft)'].round(1)

In [86]:
#Cleaning weight column
def clean_weight(val):
    if pd.isna(val):
        return np.nan

    if isinstance(val, (int, float)):
        return int(round(float(val)))

    val = str(val).lower().strip()

    match = re.search(r'\d+(\.\d+)?', val)
    if match:
        return int(round(float(match.group())))

    return np.nan

In [87]:
df['Weight(in kg)'] = df['Weight(in kg)'].apply(clean_weight)

In [88]:
df['Weight(in kg)'].isna().sum()

np.int64(0)

In [90]:
df.iloc[:, :4].head(20)

    Semester  Age(in years)  Height(in ft)  Weight(in kg)
0          5             24            5.5             54
1          8             21            5.1             46
2          8             22            5.0             50
3          7             22            5.2             63
4          5             23            5.8             62
5          4             22            5.6             56
6          7             22            5.6             73
7          6             23            5.8             72
8          7             22            5.7             58
9          5             22            5.6             63
10         6             22            5.6             70
11         5             22            5.8             65
12         5             22            6.0             73
13         4             22            4.0             57
14         4             22            8.0             55
15         4             22            5.6             71
16         8             22            5.3             64
17         7             22            5.2             45
18         8             23            5.1             63
19         5             21            5.2             52